[theme]
base="light"
primaryColor="#FF69B4"               # Hot Pink
backgroundColor="#FFF0F5"            # Soft pink (lavender blush)
secondaryBackgroundColor="#FFE4E1"   # Misty rose
textColor="#3A3A3A"                  # Deep gray
font="sans serif"

